### ISSUE TITLE
Some Grammar issues.

### ISSUE THREAD

**Issue by UrsZeidler** [webdaford/smart-contract-tools#19]
After checking with a lot of code examples I found some small issues I collect here:

```
      if((amount / 1000000000000000) % 2 == 0){ 
```

**error:** For input string: "1000000000000000"

```
             delete items[addr];
```

**error:** mismatched input '[' expecting ';'
Delete is a reserved word.  I could not figure out when it was introduced, maybe it was always there.
See http://solidity.readthedocs.io/en/stable/types.html?highlight=delete#delete

Support for the  ternary operator: x ? y : z
Introduced in 0.2.1

A Typecast  can be a qualifier

```
                   address( d.owner ).send( d.price ); // The money goes to the owner
```

**error:** mismatched input '.' expecting ';'

**Comment by webdaford** [comment]
Good list.  I'm mostly going on memory when I look at Solidity, so I had to do a search on "delete" to see the context.  Except, I couldn't find the string "delete" in the grammar file or the rest of the project (must be me).  
I took a quick scan through the test cases the other day and "discovered" that many were skipped (by me), not something I remembered about the code base.  I expect that there could be more grammar issues lurking.

**Comment by webdaford** [comment]
The issue with parsing large integers is fixed.

**Comment by UrsZeidler** [comment]
NIce.

**Comment by webdaford** [comment]
maybe break these out as individual issues?

**Comment by UrsZeidler** [comment]
done.
So I close this.
