### ISSUE TITLE
Support the delete operation.

### ISSUE THREAD

**Issue by UrsZeidler** [webdaford/smart-contract-tools#21]
Solidity provides the delete command. Some of the possible expressions are not supported by the Grammar.

```
         delete items[addr];
```

error: mismatched input '[' expecting ';'
Delete is a reserved word. I could not figure out when it was introduced, maybe it was always there.
See http://solidity.readthedocs.io/en/stable/types.html?highlight=delete#delete

**Comment by webdaford** [comment]
I think this can be closed..?

**Comment by UrsZeidler** [comment]
It can.
